---
apiVersion: v1
kind: Secret
metadata:
  name: sonar-postgresql
  namespace: sonarqube
data:
    postgresql-password: abc
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
data:
    postgres-password: abc
type: Opaque
